package com.ifucolo.taskmanager.viewmodel.generics

sealed class ViewState<out T> {
    object Loading : ViewState<Nothing>() {
        override fun equals(other: Any?) = other is Loading
        override fun hashCode() = javaClass.hashCode()
    }

    object Error : ViewState<Nothing>() {
        override fun equals(other: Any?) = other is Error
        override fun hashCode() = javaClass.hashCode()
    }

    data class Data<T>(val data: T) : ViewState<T>() {
        // Equality and hash code are generated by the data class for `data` field.
    }
}