name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'  # Set to Java 18
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools-version: 31.0.0
        components: platform-tools

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Lint Code
      run: ./gradlew lint

    - name: Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.32.0
      with:
        api-level: 29  # Use a stable API level like 29
        target: google_apis
        arch: x86_64
        profile: Pixel_4
        script: ./gradlew connectedAndroidTest  
        emulator-options: "-no-snapshot-save -noaudio -no-boot-anim -gpu swiftshader_indirect"  # Use software rendering
        disable-animations: true  # Disable animations for a more stable CI environment
        disable-linux-hw-accel: true  # Force disable hardware acceleration on Linux
        verbose: true  # Set to true for more detailed logs

    - name: Wait for Emulator to Boot
      run: |
        adb wait-for-device
        adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

    - name: Build Release APK
      run: ./gradlew assembleRelease
